<?php
function user_is_admin(){
global $user;
$adminRoles= array('administrator');
// miKrumo($user);
$check = array_intersect($adminRoles, array_values($user->roles));
$adminAble = empty($check) ? FALSE : TRUE;

if($user->uid==1) $adminAble = TRUE;
return $adminAble;
}
	
function user_is_editor(){
global $user;
$adminRoles= array('administrator','editor','redactor','diseñador');
$check = array_intersect($adminRoles, array_values($user->roles));
$adminAble = empty($check) ? FALSE : TRUE;
return $adminAble;
}
	
function miKrumo($var){
	// if(!user_is_admin()) return false;
		
		if (!function_exists('krumo')){
	 include_once  drupal_get_path('module', 'devel'). '/krumo/class.krumo.php';
			}
	echo "<div id='krumoDiv'>	";	
	krumo($var);
	echo"</div>";
}


function _taxonomy_get_real_tree($vid){
  $result_tree = array();
  $terms = array();
  foreach(taxonomy_get_tree($vid) as $term){
    if(isset($terms[$term->tid])){
      $term->children = $terms[$term->tid]->children;
      $terms[$term->tid] = $term;
    }else{
      $terms[$term->tid] = $term;
    }

    if($term->depth === 0){
      $result_tree[$term->tid] = &$terms[$term->tid];
      continue;
    }

    foreach($term->parents as $tid){
      if($tid){
        if(!isset($terms[$tid])){
          $terms[$tid] = new stdClass();
        }
        $terms[$tid]->children[$term->tid] = &$terms[$term->tid];
      }
    }
  }
  return $result_tree;
}

/**
* Trim a post to a certain number of characters, removing all HTML.
*/
function trim_text($text, $length = 150) {
  // remove any HTML or line breaks so these don't appear in the text
  $text = trim(str_replace(array("\n", "\r"), ' ', strip_tags($text,'<a>')));
  $text = trim(substr($text, 0, $length));
  $lastchar = substr($text, -1, 1);
  // check to see if the last character in the title is a non-alphanumeric character, except for ? or !
  // if it is strip it off so you don't get strange looking titles
  if (preg_match('/[^0-9A-Za-z\!\?]/', $lastchar)) {
    $text = substr($text, 0, -1);
  }
  // ? and ! are ok to end a title with since they make sense
  if ($lastchar != '!' and $lastchar != '?') {
    $text .= '...';
  }

  return $text;
}