<?php

/**
 * Implementation of hook_menu().
 */
function purl_static_menu() {
  $items['admin/settings/purl/static'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Static PURLs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('purl_static_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'weight' => 3,
  );
  return $items;
}

function purl_static_form() {
  $form = array();
  $form['purl_static'] = array(
    '#type' => 'textarea',
    '#title' => t('Static PURLs'),
    '#default_value' => variable_get('purl_static', ''),
    '#description' => t('Enter a pipe-delimited list of desired PURL modifiers and Context machine names, one per line.  For example, "backstage|backstage_context", if the Path PURL Processor is enabled, would result in URLs beginning with "backstage" activating the "backstage_context" Context.'),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_purl_provider().
 */
function purl_static_purl_provider() {
  return array(
    'purl_static' => array(
      'name' => t('PURL Static'),
      'description' => t('Allows manually creating static Persistent URLs (based on admin-entered identifiers, rather than site content).  Upon encountering a static PURL, the selected Context is activated.'),
      'callback' => 'purl_static_purl_active',
      'example' => 'backstage',
    ),
  );
}

/**
 * Implementation of hook_purl_modifiers().
 */
function purl_static_purl_modifiers() {
  $staticPURLs = explode("\n", variable_get('purl_static', ''));
  $modifiers = array();
  foreach ($staticPURLs as $staticPURL) {
    $e = explode('|', $staticPURL);
    $modifiers[] = array('value' => $e[0], 'id' => $e[1]);
  }
  return array('purl_static' => $modifiers);
}

function purl_static_purl_active($context) {
  $c = context_load($context);
  context_set('context', $c->name, $c);
}
