<?php
// $Id:$


/* Implementation of hook_menu().
*/
// Implements hook_theme
function social_links_theme(){
    $themes=array();
        $themes['social_addthis']=array(
            // Optionally, you can make the theme use a template file:
            // this line references the file "mydatafile.tpl.php" in the same folder as the module or in the folder of the active theme
            'template' => 'social_links',
            // these variables will appear in the template as $var1 and $var2
            'arguments' => array('node'=>null)
            
        );
	return  $themes;
  
} 
 
/*function social_links_preprocess_node(&$vars, $hook){
	
	// krumo::get();
	$vars['social_addthis']=theme('social_addthis');
	miKrumo($vars);
	}*/ 
