<?php

/**
 * implementation of hook_menu
 */
function drupento_user_migrate_menu() {
	$items = array();
	
	$items['admin/settings/drupento/migrate-users'] = array(
		'title' => 'User Migration',
		'page callback' => 'drupento_user_migrate_migrate_users',
		'access arguments' => array('migrate drupal users to magento')		
	);
	
	return $items;
}

/**
 * migration routine using batch api 
 */
function drupento_user_migrate_migrate_users() {	
	$operations = array();

	$limit = variable_get('drupento_user_migrate.batch_size', 1);
	$result = db_query('SELECT uid from {users} WHERE uid > %d ORDER BY uid ASC', variable_get('drupento_user_migrate.exclude_admin', false) ? 0 : 1);

	while( $row = db_fetch_object($result) ) {
		$user = user_load(array('uid' => $row->uid));
		array_push( $operations, array('drupento_user_migrate_migrate_user', array($user)) );
	}
				
	$batch = array(
		'operations' => $operations,
		'finished' => 'drupento_user_migrate_migrate_finished',
		'title' => t('Migrating Drupal users to Magento...'),
		'init_message' => t('Beginning user migration'),
		'progress_message' => t('Migrated @current of @total users.'),
		'error_message' => t('The migration process has encountered an error.')
	);

	batch_set($batch);
	batch_process();
}

/**
 * Batch finished callback
 */
function drupento_user_migrate_migrate_finished() {
	drupal_set_message(t('Drupal user migration complete'));
	drupal_goto('/');
}

/**
 * Migrate a single user
 */
function drupento_user_migrate_migrate_user($user, &$context) {

	// prime the sandbox if not yet initialized
	if (!isset($context['sandbox']['progress'])) {
		$context['finished'] = 0;		
		$context['sandbox']['progress'] = 0;
		$context['sandbox']['current_user'] = variable_get('drupento_user_migrate.include_admin', false) ? 1 : 0;
		$context['sandbox']['max'] = db_result(db_query('SELECT COUNT(DISTINCT uid) FROM {users} WHERE uid > %d', variable_get('drupento_user_migrate.exclude_admin', false) ? 0 : 1));
	}
	
    $context['sandbox']['progress']++;
    $context['sandbox']['current_user'] = $user->uid;

	if(drupento_auth_mage_customer($user)) {
		$context['message'] = t('User \'%user\' already has Magento account', array('%user' => $user->name));			
	}
	else {
		$context['message'] = t('Now processing \'%user\'', array('%user' => $user->name));			
		_drupento_user_migrate_create_mage_user($user);	
	}

	$context['finished'] = 1;
}

/**
 * Migration SOAP call
 */
function _drupento_user_migrate_create_mage_user($user) {
	$store_id = variable_get('drupento_magento_store_id', 1);
	$website_id = variable_get('drupento_magento_website_id', 1);

	$account_details = array(
		'email'      		=> $user->mail,
		'password_hash'		=> $user->pass,
		'store_id'   		=> $store_id,
		'website_id' 		=> $website_id
	);
	
	$additional_details = drupento_auth_get_registration_additional_fields_array( (array)$user );
	$account_details = array_merge($account_details, $additional_details);
	
	$created = Drupento::Call('customer.create', array($account_details));	
	if( !is_numeric($created) ) {
		drupal_set_message(t('There was a problem fully creating your customer account. Please contact a site administrator'));
	}
}

/**
 * simple logging for testing
 */
function drupento_user_migrate_log($message) {
	if( is_array($message) ) {
		file_put_contents( dirname(__FILE__) . '/drupento_user_migrate.log', print_r($message,1) . "\n", FILE_APPEND );
	}
	else {
		file_put_contents( dirname(__FILE__) . '/drupento_user_migrate.log', $message . "\n", FILE_APPEND );
	}
}
