<?php
function views_alters_preprocess_views_view($vars){
	 // $view->set_offset(1);
	 
	/* $vars['view']->set_offset('1');
	 miKrumo($vars['view']);
	$vars['view']->display_handler->set_option('offset', 1);
	
	$handler=$vars['view']->display_handler;
	  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
$handler->display->display_options['pager']['options']['offset'] = '1';*/
/*$view=$vars['view'];

$view->query->offset=1;
$view->query->pager->options['offset']=1;

miKrumo($view);*/
/*if($view->current_display == 'page_seccion'){
	$handler=$view->display_handler;
$handler->options['pager']['options']['offset']=1;


}*/
$view=$vars['view'];
// && $view->current_display == 'attachment_1'
if ($view->name == 'lista_secciones' ) {
//miKrumo($view);
		// miKrumo($view);
		//if($view->exposed_raw_input)
		/**if(!empty($_REQUEST['terms'])){
		// $handler->options['pager']['options']['offset']=0;
		}*/
		if(!empty($view->exposed_raw_input['terms'])){
		// miKrumo($view);
		if($view->current_display=="attachment_1"){
			
			unset($view->result);
			$view->disabled=true;
			
			}
		//unset($view->attachment_before);
		}
		
		}
		
	}

/**
* Implementation of hook_views_pre_execute().
*/
/*function views_alters_views_pre_view(&$view) {
	echo "views_alters_views_pre_view";
	 miKrumo($view );
}*/
function views_alters_views_pre_build(&$view) {
	
   
  if ($view->name == 'lista_secciones' ) {
	/* miKrumo('views_alters_views_pre_build' );*/
 // miKrumo($view->filter['keys'] );

 $handler=$view->display_handler;
 
 if($view->current_display == 'page_seccion'){
	$handler->options['pager']['options']['offset']=1;
	if(!empty($_REQUEST['terms'])){
		// si hay busqueda no queremos offset porque ya ocultamos el destacado
		$handler->options['pager']['options']['offset']=0;
		}
	}
	
	if($view->current_display == 'attachment_1'){
		if(!empty($_REQUEST['terms']) ){
			// esto oculta el attachment si hay busqueda
			$view->built=true;
			return NULL;
			
			}
	}


  }
  
  
/*
	  //$view->set_offset(1);
	  $view->display_handler->options['offset']=1;
	  $view->display_handler->options['pager']['offset']=1;
	  
	  $view->display_handler->override_option('items_per_page',1);*/
	  
      

    // Get the page from the URL.
   //$page = !empty($_GET['page']) ? $_GET['page'] : 0;   
	// firep($page);    
    // Increase the offest according to the page.
  // if($page>0) $view->set_offset(0);
   
   //$view->display['page_seccion']->display_options['pager']['options']['offset'] = '1';

    // miKrumo($view->display['page_seccion']);
  
}
?>