<?php
// $Id:



/* ---- Hook implementation ---- */



/**
 * Implementation of hook_block
 */
function popup_menu_block($op = 'list', $delta = 0, $edit = array()){

  switch($op){

    case 'list':

      $menus = menu_get_menus();
      $menu_blocks = array();

      foreach($menus as $id => $menu){
        $menu_blocks[$id]['info'] = 'Popup menu: '.$menu;
      }
      return $menu_blocks;

    case 'configure': 
      module_load_include('inc', 'popup_menu', 'includes/popup_menu.util');
      return popup_menu_block_form($delta);

    case 'save':
      module_load_include('inc', 'popup_menu', 'includes/popup_menu.util');
      popup_menu_block_form_save($delta, $edit);
    break;

    case 'view':

      module_load_include('inc', 'popup', 'includes/popup.api');
      module_load_include('inc', 'popup_menu', 'includes/popup_menu.util');

      $settings = _popup_menu_settings();
      $settings = $settings[$delta]
        ? $settings[$delta]
        : _popup_menu_default_settings();

      $attributes = array();
      $attributes['format'] = $settings['format'];
      $attributes['menu'] = $delta;
      $attributes['title'] = $settings['override-title'] != ''
        ? $settings['override-title']
        : FALSE;

      return array(
        'content' => popup($attributes),
      );

  }

}



/**
 *  Implementation of hook_features_api
 */
function popup_menu_features_api() {
  return array(
    'popupmenu' => array(
      'name' => t('Popup menus'),
      'default_hook' => 'popupmenu_defaults',
      'default_file' => FEATURES_DEFAULTS_INCLUDED_COMMON,
      'file' => drupal_get_path('module', 'popup_menu') .'/includes/popup_menu.features.inc',
    ),
	);
}